# Generated by Django 5.1.4 on 2024-12-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersazienda',
            options={},
        ),
        migrations.AlterModelTable(
            name='usersazienda',
            table=None,
        ),
    ]
