# Generated by Django 5.1.5 on 2025-01-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usersazienda_options_alter_usersazienda_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersazienda',
            options={'managed': True},
        ),
       
        migrations.AlterField(
            model_name='fatture',
            name='n_fattura',
            field=models.CharField(blank=True, db_column='n_fattura', max_length=40, null=True),
        ),
        migrations.AlterModelTable(
            name='usersazienda',
            table='usersazienda',
        ),
    ]
