# Generated by Django 5.1.5 on 2025-01-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_usersazienda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersazienda',
            table='userazienda',
        ),
    ]
