# Generated by Django 5.1.5 on 2025-01-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usersazienda_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersazienda',
            table='usersazienda',
        ),
    ]
