# Generated by Django 5.1.5 on 2025-01-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_usersazienda_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='logo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
