# Generated by Django 5.1.5 on 2025-01-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_azienda_logo'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='assegnato_cantiere',
            name='ore_lavorate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
