# Generated by Django 5.1.5 on 2025-01-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fornitori_azienda_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='cantiere',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
