# Generated by Django 5.1.5 on 2025-02-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_fornitori_azienda_alter_cantiere_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazzino',
            name='ordine',
        ),
        migrations.AddField(
            model_name='magazzino',
            name='azienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_magazzino', to='home.azienda'),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='tipologia',
            field=models.CharField(choices=[('SE', 'SERVIZIO'), ('MA', 'MATERIALE'), ('NO', 'NOLEGGIO')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
